CS = {
    "road": [
        "A road typically has the following features:* A surface, which can be made of asphalt, concrete, dirt, gravel, or other materials* A width, which can vary depending on the road's design and.",
        "A road has asphalt or concrete surface, lane markings, traffic signals, road signs, sidewalks on either side, shoulders, medians, curbs, gutters, storm drainage systems, streetlights, and.",
        "A road has a surface, width, lane markings, shoulders, medians, traffic signals, signs, curves, hills, and intersections.",
        "A road typically has the following features:a surface, which can be made of asphalt, concrete, dirt, gravel, or other materialsa width, which can vary depending on the purpose of the road and the.",
        "A road has asphalt or concrete surface, painted lines to separate traffic lanes, sidewalks or pedestrian paths, road signs and signals, streetlights, and possibly medians or central reservations.",
        "A road is a long, wide, and flat stretch of land that is usually paved or covered with gravel.",
        "A road has:* a long open strip* of flat or undulating terrain* with a defined surface* often made of asphalt or concrete* bordered by* marked lane lines* and occas.",
        "A road has a smooth surface, clear markings, and different types of vehicle lanes, including one or more lanes for each direction of travel, bicycle lanes, and sometimes multiple lines of traffic in each lane.",
        "A road has asphalt, lanes, concrete, shoulders, guardrails, traffic signals, pavement markings, and sometimes a median.",
        "A road has pavement, markings, shoulders, medians, traffic signs, roadside vegetation, and occasional obstacles or construction.",
        "A road is linear, paved, and marked with lanes.",
        "A road is a rectangular, black asphalt surface with painted white and yellow lines and occasional road signs and markers.",
        "A road is a strip of pavement that connects two points, often with a centerline and lines dividing the lanes.",
        "A road is a stretch of land designed to facilitate transportation of people and goods from one place to another.",
        "A road is a stretch of pavement or other surface that is designed for vehicular traffic.",
        "A road is a linear infrastructure that connects different locations and enables transportation of people and goods.",
        "A road is wide, well-maintained, and lined with trees.",
        "A road is a critical component of modern urban infrastructure, serving as a dominant visual feature within urban landscapes.",
        "Sure, here's one possible way to describe the unique visual appearance of a road:A road is generally a long and linear feature that is designed to facilitate transportation of people and goods from one place to another.",
        "A road is."
    ],
    "sidewalk": [
        "A sidewalk has a surface,..",
        "A sidewalk has a flat, paved surface, typically made of concrete or asphalt, and is placed alongside a road or street to provide a safe walking area for pedestrians.",
        "A sidewalk has concrete, pavement, asphalt, bricks, stones, stripes, cracks, worn-out, wet, dry, dirty, slick, smooth, uneven, raised, sunken, broken, loose.",
        "A sidewalk typically has a flat, rectangular surface made of concrete or asphalt, and is designed for pedestrian traffic.",
        "A sidewalk typically has:* A walking surface made of concrete, pavement, or bricks,* B bounded by curbs or a boundary of some sort,* C often traversed by pedestrians,.",
        "A sidewalk typically has a concrete or asphalt surface, which is rectangular in shape and laid out in a straight or curved pattern.",
        "A sidewalk has:-a surface made of concrete, brick, or pavement-a width ranging from 3-6 feet-a smooth or slightly sloped incline to facilitate walking-edges that may.",
        "A sidewalk typically has a surface made of concrete, brick, or asphalt, and is designed for pedestrians to walk on.",
        "A sidewalk has a surface, borders, and possibly amenities like benches or planters.",
        "A sidewalk has:* A raised walking surface* B a paved or concrete surface* C a width suitable for one or two pedestrians to walk side by side* D bordered with curbs or ed.",
        "A sidewalk is a linear, paved pathway designed for pedestrian travel, often embedded within urban landscapes.",
        "A sidewalk is a paved pathway designed for pedestrians, typically found in urban and suburban areas.",
        "A sidewalk is a durable, visually appeal-ing, and functional surface that is designed for pedestrians.",
        "A sidewalk is typically a narrow, paved pathway that is designed for pedestrians to use as a means of transportation or for recreational purposes.",
        "A sidewalk is a concrete or asphalt-paved path for pedestrians that typically runs along the side of a road or street.",
        "A sidewalk is a concrete or brick-paved pathway that runs alongside a street or road, providing a safe, accessible route for pedestrians.",
        "A sidewalk is a raised and paved pathway designed for pedestrian use.",
        "A sidewalk is concrete, even, flat, and rectangular.",
        "A sidewalk is typically a flat, paved surface that is designed for pedestrian use.",
        "A sidewalk is flat, rectangular, and made of concrete or brick."
    ],
    "building": [
        "A building typically has walls, a roof, windows, and a foundation.",
        "A building has walls, a roof, windows, and doors.",
        "A building has walls, a roof, windows, and a foundation.",
        "A building typically has the following features:* A foundation, which is the structural base that supports the building's weight and distributes it evenly across the land.",
        "A building is typically composed of several components, such as walls, floors, ceilings, windows, doors, and a roof.",
        "A building typically has walls, a roof, windows, and a door.",
        "A building has walls, a roof, and windows.",
        "A building has walls, windows, doors, a roof, and a foundation.",
        "A building has walls, a roof, windows, and a door.",
        "A building typically appears as a structure with walls, a roof, and windows.",
        "A building is Architecturally distinctive, Structurally unique, and Historically significant.",
        "A building is unique in its visual appearance, characterized by a combination of architectural style, materials used, and design elements.",
        "A building's visual appearance can be described as unique, distinctive, and eye-catching.",
        "A building's unique visual appearance can be described as follows:A building is distinctive, unique, striking, and recognizable.",
        "A building's unique visual appearance can be described as A - having a distinctive architectural style, B - showcasing unique multicolored brickwork facade, and C - topped with unique helical-shaped roof.",
        "A building is architecturally unique, structurally sound, and aesthetically pleasing.",
        "A building is architecturally unique, aesthetically pleasing, and contextually appropriate, where architecturally unique refers to the building's design that stands out from others, aesthetically pleasing refers to its visually attract.",
        "A building's unique visual appearance can be described as A) architecturally distinctive, B) visually striking, and C) aesthetically pleasing.",
        "A building's unique visual appearance can be described as A: distinctive, B: striking, C: architectural, and D: contextual.",
        "A building's unique visual appearance can be described using various adjective phrases to describe its architectural style, materials, colors, shape, and other characteristics."
    ],
    "wall": [
        "A wall has a solid appearance and is typically made of materials such as brick, concrete, or stone.",
        "A wall has a solid, flat surface, typically made of materials such as brick, stone, concrete, or wood.",
        "A wall is a structure that provides a barrier or separation between two spaces or areas.",
        "A wall has:* A horizontal surface, typically made of brick, stone, concrete, or wood, with a flat or slightly inclined profile.",
        "A wall has a surface, which can be smooth or textured.",
        "A wall has a surface, a color, a texture, a height, and a material.",
        "A wall typically has a solid structure, made up of materials such as brick, stone, concrete, or wood.",
        "A wall has bricks, mortar, plaster, paint, a surface, a texture, a color, a height, a width, a length, a foundation, a support, and a purpose.",
        "A wall has several components including:* A surface: which is typically flat and may be rough or smooth.",
        "A wall has:1.",
        "A wall is typically composed of rectangular shapes made of bricks, concrete, or other materials.",
        "A wall is solid, sturdy, and typically rectangular in shape.",
        "a wall is textured, solid, and monochromatic.",
        "A wall is a vertical structure that serves as a barrier or divide.",
        "A wall is textured, solid, and towering.",
        "A wall is an upright, surrounding barrier typically made of bricks, stones, wood, or concrete.",
        "A wall is robust, imposing, and ideally adorned with tempting graffiti.",
        "A wall is solid, imposing, and decorated.",
        "A wall is typically monochromatic, with a flat, even surface.",
        "A wall is a solid, rectangular structure that serves as a barrier or division between spaces."
    ],
    "fence": [
        "A fence typically has posts, rails, and crossbars, which are made of materials such as wood, metal, or plastic.",
        "A fence typically has corners, slats, and a frame.",
        "A fence typically has:* Posts: vertical members that provide support and structure to the fence* Rails: horizontal members that connect the posts and form the top and bottom sections of the fence* Panels: sections.",
        "A fence typically consists of several components including:* vertical boards or slats, made of materials such as wood, metal or vinyl, spaced closely together to create a barrier.",
        "A fence consists of slats, posts, and rails.",
        "A fence typically has vertical posts, horizontal rails, and boards or sheets of material stretched between them to create a barrier.",
        "A fence typically has a set of vertical slats, also known as pickets or rails, that are spaced closely together to create a barrier.",
        "A fence typically consists of a series of vertical posts or rails that are connected by horizontal crossbars, creating a barrier or enclosure.",
        "A fence typically has posts, rails, and panels that are joined together with hardware such as hinges, latches, and screws.",
        "A fence has horizontal bars, vertical posts, and a solid base.",
        "A fence is typically made of wood, metal or concrete and has a linear or curvilinear shape.",
        "A fence is typically a structure made of vertical boards or slats, joined together by horizontal rails, and supported by posts or pillars.",
        "A fence is long, sturdy, and made of wood.",
        "A fence is usually made up of horizontal boards, vertical posts, and often includes decorative elements such as latticework or spears.",
        "A fence is typically a solid barrier made of materials such as wood, metal, or plastic, designed to enclose a particular area.",
        "A fence is typically a structure made of horizontal boards or slats that are attached to vertical posts.",
        "A fence is typically made of wooden planks or metal, and it is usually tall and sturdy, with vertical bars or slats.",
        "A fence is linear, restrictive, and varying in height.",
        "A fence is typically made of wood, metal, or plastic, and may have one or more rows of slats or pickets.",
        "A fence is typically made up of vertical posts or slats that are secured together to create a barrier."
    ],
    "pole": [
        "A pole has a cylindrical shape, a smooth or rough surface, and a tapered end.",
        "A pole has:* A cylindrical shape with a circular cross-section* A length ranging from a few meters to hundreds of meters* A diameter ranging from a few centimeters to several meters* A.",
        "A pole has:1.",
        "A pole has a cylindrical shape, a smooth or rough texture, and a tapered or rounded tip.",
        "A pole has a cylindrical shape, a long and slender body, and a pointed or flat tip, and it typically has smooth or rough surfaces with a length of around 6-10 feet and a diameter of around 2-.",
        "A pole is a vertical structure that is typically round and cylindrical in shape, with a smooth surface.",
        "A pole has a cylindrical shape, with a pointed or rounded top, and a flat bottom.",
        "A pole has a cylindrical shape, a vertical orientation, and a smooth or rough surface.",
        "A pole has a cylindrical shape, a vertical orientation, and a smooth or textured surface.",
        "A pole can have several characteristics that define its appearance.",
        "A pole is typically tall, cylindrical, and made of wood, metal, or plastic.",
        "A pole is typically cylindrical in shape, made of metal or other sturdy materials, and often has a smooth or textured surface.",
        "A pole is tall, slender, and cylindrical in shape.",
        "A pole is typically tall, slender, and cylindrical in shape, with a smooth or textured surface.",
        "A pole is tall, slender, and cylindrical in shape.",
        "A pole is tall, cylindrical, and made of wood or metal.",
        "A pole is cylindrical, vertical, and often made of materials such as wood, metal, or plastic.",
        "A pole is typically a cylindrical object with a smooth or textured surface.",
        "a poles is tall, cylindrical, and made of material, such as wood or metal.",
        "A pole is usually tall and straight, with a circular cross-section."
    ],
    "trafficlight": [
        "A trafficlight has a red, yellow, and green light.",
        "A trafficlight has:1.",
        "A traffic light has a red light, a yellow light, and a green light.",
        "A trafficlight has a red, yellow, and green light, which are positioned one above the other on a tall post.",
        "A traffic light has a red light, a yellow light, and a green light.",
        "A trafficlight has a red, yellow, and green light.",
        "A trafficlight has a round, red, and green.",
        "A trafficlight has a red light, a yellow light, and a green light.",
        "A trafficlight has a red, yellow, and green light.",
        "A trafficlight has a red, yellow, and green light that alternates in sequence.",
        "A trafficlight is typically A red, yellow, and green B light-emitting C device that is used to Reroute traffic and control the flow of vehicular and pedestrian traffic.",
        "A trafficlight is red, yellow, and green, with each color occupying one of the three sections of the trafficlight, and each section having a different shape.",
        "A trafficlight is typically a three-sided, red, yellow, and green, illuminated sign, typically mounted on a poles and positioned at intersections or other locations to regulate traffic flow.",
        "A trafficlight is a set of three distinct colored lights (red, yellow, and green) arranged in a vertical stack on a pole, typically located at intersections to regulate traffic flow.",
        "A trafficlight is usually a tall, cylindrical-shaped object made up of red, yellow, and green lights arranged vertically from bottom to top.",
        "A trafficlight is a device that controls and regulates the flow of vehicular and pedestrian traffic by signaling the time for movement.",
        "A trafficlight is typically a red, yellow, and green speaker inserted into a 3D model of a trafficlight using Blender's Object Properties.",
        "A trafficlight is red, yellow, green, with a rectangular shape, a round top, and a red light on the top left, a yellow light in the center, and a green light on the top right.",
        "A trafficlight is a multicolored, signaling device, consisting of a set of three lights, typically red, yellow, and green, mounted on a tall pole, with a control mechanism to switch between the colors, designed to regulate traffic.",
        "A trafficlight is typically a three-sided signal with a red, yellow, and green panels, each with a circular shape and a raised border."
    ],
    "trafficsign": [
        "A trafficsign has colors, shapes, and symbols that indicate traffic rules and regulations.",
        "A trafficsign has a rectangular shape with a red base and white lettering.",
        "A trafficsign typically consists of shapes, colors, and symbols that convey information about road conditions, directions, speed limits, and other regulations to drivers and pedestrians.",
        "A trafficsign has a colorful design, bold lettering, and various symbols or images to convey information about traffic regulations, directions, and road conditions.",
        "A trafficsign primarily consists of shapes, colors, and text that communicate information about road rules, regulations, and directions.",
        "A trafficsign has a rectangular shape with a red background, a white crossbar, and black lettering.",
        "A trafficsign typically has the following components:* A color scheme: Traffic signs usually have a color scheme that is consistent with the standards set by the American Association of State Highway and Transportation Officials (AASHTO.",
        "A trafficsign has a red background, white letters, and a hexagonal shape.",
        "A trafficsign typically has a shape, color, and message that convey information about traffic rules, speed limits, road conditions, or upcoming construction or hazards.",
        "A trafficsign has a red circle and a diamond shape, with a white border and bold black lettering.",
        "A traffic sign is typically a three-dimensional object with a rectangular shape, featuring information and directional symbols to regulate and guide traffic.",
        "A trafficsign is typically rectangular in shape with a solid or outline color design representing a specific traffic control message and intended meaning.",
        "A trafficsign is typically a rectangular-shaped object with a solid color background, featuring bold white or yellow lettering and symbols that communicate information about road conditions, directions, and other important safety messages.",
        "A trafficsign is typically a rectangular or square shaped object with parallel edges and a flat surface, painted with bright colors and symbols to convey traffic information.",
        "A trafficsign is colorful, rectangular, and illuminated.",
        "A trafficsign is typically rectangular in shape, with a color scheme of red, white, and black, featuring bold lettering and symbols to convey important information about road conditions, speed limits, and other traffic instructions.",
        "A trafficsign is typically a rectangular-shaped object with a red or yellow background and black or white letters or symbols.",
        "A trafficsign is typically octagonal in shape and features bold, contrasting colors and graphics that make it easily noticeable and recognizable.",
        "A trafficsign is typically rectangular in shape with a red or yellow background, and features bold black or white letters or symbols to indicate the type of traffic rule or warning it represents.",
        "A trafficsign is round, sturdy, and eye-catching."
    ],
    "vegetation": [
        "A vegetation typically has a variety of plant life, including grasses, trees, shrubs, and vines.",
        "A vegetation typically has leaves, stems, and roots.",
        "A vegetation has various features that can be described as follows:1.",
        "A vegetation typically has a variety of features that describe its appearance and characteristics.",
        "A vegetation can have many different characteristics depending on the type of vegetation and its environment.",
        "A vegetation typically has a variety of features that describe its appearance, including:* Height: vegetations can range from small, low-lying plants to tall trees.",
        "Sure, here's an answer in the requested format:A vegetation typically has a combination of various plants and trees with different heights, shapes, and colors.",
        "A vegetation typically consists of various plant species that grow together in a specific environment.",
        "A vegetation typically has a variety of A, B, and C to describe its appearance and characteristics.",
        "A vegetation has various characteristics that can vary depending on the type of vegetation in question.",
        "A vegetation is green, leafy, and diverse, where green refers to the typical color of most vegetations, leafy describes the presence of foliage or leaves, and diverse refers to the variety of plant species that make up the veget.",
        "A vegetation is diverse, vibrant, and dynamic, featuring various shapes, sizes, and colors, with different species and textures intertwining to form a rich and complex tapestry of life.",
        "A vegetation is visually complex, diverse, and dynamic, offering a wide range of colors, textures, and shapes.",
        "A vegetation is green, leafy, and diverse in texture and shape.",
        "A vegetation is lush, diverse, and vibrant, with a wide range of colors and textures.",
        "A vegetation is diverse, dynamic, and colorful, featuring a wide range of varying plant species that contribute to its unique visual appearance.",
        "A vegetation is diverse, lush, and dynamic, with a wide range of shapes, sizes, textures, and colors.",
        "A vegetation is dynamic, diverse, and colorful, with a variety of textures and shapes.",
        "A vegetation is green, leafy, and lush, with a diverse range of shapes, sizes, and textures depending on the type of vegetation.",
        "A vegetation is diverse, colorful, and dynamic."
    ],
    "terrain": [
        "A terrain has elevation, slope, contour, vegetation, rocks, soil, water features, and landforms such as mountains, valleys, and plateaus.",
        "A terrain can have different features that contribute to its overall appearance and characteristics.",
        "A terrain has elevation changes, vegetation, water sources, geological formations, and landforms.",
        "A terrain has various features that can be used to describe it.",
        "A terrain is a natural surface, typically a land area, with.",
        "A terrain has various features, including elevation, topography, geology, vegetation, and waterways.",
        "A terrain typically has a variety of features, including:* Elevations: hills, mountains, valleys, and plateaus* Geological formations: rocks, boulders, caves, and cliffs* Veg.",
        "A terrain is a land surface, typically with variations in elevation, slope, and vegetation.",
        "A terrain has various features that can be described using noun phrases.",
        "A terrain has diverse physical features, vegetation, and landforms that create a unique landscape.",
        "A terrain is diverse, irregular, and ever-changing, with various features such as mountains, valleys, hills, plains, and plateaus.",
        "A terrain can be described as having a unique visual appearance that is characterized by its shape, color, and texture.",
        "A terrain can be described as having a unique visual appearance in terms of its topography, geology, and vegetation.",
        "A terrain is diverse, irregular, and textured, where diversity refers to the variety of features such as hills, valleys, and plains, and irregularity refers to the unevenness and complexity of the terrain's shape, and.",
        "A terrain is diverse, rugged, and scenic.",
        "It's difficult to describe the visual appearance of a terrain without more context.",
        "A terrain is diverse, dynamic, and ever-changing.",
        "A terrain can be described as having a unique visual appearance that exhibits features such as its topology, the density of its vegetation, the color of its soil, and the presence or absence of water bodies.",
        "A terrain can be described as having a unique visual appearance, which can be characterized by a combination of different adjective phrases.",
        "A terrain can have a unique visual appearance based on various factors including its geological features, vegetation, topography, and human influence."
    ],
    "sky": [
        "A sky has colors, clouds, stars, and sometimes shapes that change with time of day and weather conditions.",
        "A sky can have many different characteristics, depending on factors such as time of day, weather conditions, and location.",
        "A sky can have a variety of characteristics depending on factors such as time of day, weather conditions, and location.",
        "A sky can have many different features, and its appearance can vary depending on factors such as time of day, weather, and location.",
        "A sky has clouds, colors, and depth.",
        "A sky can have many different characteristics, so it can be described in various ways.",
        "A sky has depth, color, and shape.",
        "A sky has clouds, colors, lights, and movements.",
        "A sky typically appears as a vast expanse of blue, with occasional clouds and the sun or moon in the center.",
        "A sky has color, clouds, stars, and planets.",
        "A sky is vast, expansive, and ever-changing.",
        "A sky can be described as a vast and ever-changing canvas of colors, patterns, and diversity.",
        "A sky is vast, expansive, and ever-changing.",
        "A sky is awe-inspiring, vast, and ever-changing.",
        "A sky is expansive, ever-changing, and awe-inspiring.",
        "A sky is vast, expansive, and ever-changing.",
        "A sky is vast, expansive, and ever-changing.",
        "A sky is vast, expansive, and ever-changing.",
        "A sky is vast, expansive, and ever-changing.",
        "A sky is always changing, and its unique visual appearance depends on various factors such as the time of day, weather conditions, and location."
    ],
    "person": [
        "A person has a body, a face, and a personality.",
        "A person typically has a face, a body, and hands.",
        "A person has a face, eyes, ears, nose, mouth, hair, and a body.",
        "A person typically has a face, body, and limbs.",
        "A person typically has a head, torso, two arms, and two legs.",
        "A person has two arms, two legs, a torso, a head, and a face.",
        "A person has a face, hair, eyes, nose, ears, a body, a height, a weight, a gender, a skin tone, a facial expression, a posture, a style of dress, and various other characteristics.",
        "A person has eyes, nose, mouth, ears, hair, height, weight, and so on.",
        "A person typically has a body with two arms, two legs, and a head.",
        "A person typically has a face, eyes, eyebrows, a nose, ears, a mouth, hair, and arms.",
        "A person's unique visual appearance can be described using a variety of adjective phrases.",
        "A person is physically unique and can be described in various ways, such as:a person is tall, slender, with piercing blue eyes, dark brown hair, and a warm smile.",
        "A person's unique visual appearance is a combination of various physical traits such as facial features, body build, skin tone, hair texture, eye color, and other distinguishing characteristics.",
        "A person's unique visual appearance can be described in various ways, depending on the individual.",
        "A person's unique visual appearance can be described in various ways depending on their physical features, personal style, and individuality.",
        "A person's unique visual appearance is often described by various adjective phrases.",
        "A person's unique visual appearance can be described using various adjective phrases.",
        "A person's unique visual appearance can be described as a combination of various physical features.",
        "A person's unique visual appearance is a subjective assessment and can vary depending on many factors including culture, personal preferences, and individual characteristics.",
        "A person's unique visual appearance can be described using various adjective phrases."
    ],
    "rider": [
        "A rider typically has:1.",
        "A rider typically has physical characteristics that vary depending on factors such as age, height, weight, and physical build.",
        "A rider typically has the following characteristics:1.",
        "A rider typically has:* Some form of protective gear, such as a helmet and gloves.",
        "A rider has a helmet, riding boots, and a leather jacket.",
        "A rider typically has the following characteristics:* A helmet to protect their head* A motorcycle or bicycle to ride* Protective gear such as gloves, jacket, and boots*.",
        "A rider typically has:* A helmet: to protect the head* A motorcycle or bicycle: the mode of transportation* Protective gear: such as gloves, jacket, and p.",
        "A rider has a protective helmet, rugged boots, sturdy gloves, long pants, and dur.",
        "A rider has:* A helmet to protect their head* A motorcycle or bicycle as their mode of transportation* Protective gear such as gloves, a jacket, and pants.",
        "A rider typically has a person riding on top of a horse or another animal, such as a motorcycle, moped, or bicycle.",
        "A rider is confident, athletic, and stylish.",
        "A rider is confident, focused, and determined.",
        "A rider is confident, determined, and focused.",
        "A rider is confident, determined, and focused, with a well-defined physique that exudes strength and endurance.",
        "A rider is protective, focused, and determined.",
        "A rider is confident, determined, and focused on their goal.",
        "A rider is typically dressed in protective gear, such as a helmet, jacket, and gloves.",
        "I'm sorry, but I cannot provide a general answer to your question as I do not have access to visual images of riders.",
        "A rider is confident, graceful, and stylish.",
        "A rider is typically defined by their unique visual appearance, which can vary based on factors such as clothing, helmet, bike, and other accessories."
    ],
    "car": [
        "A car has four wheels, an engine, a steering wheel, headlights, taillights, a windshield, and a body.",
        "A car is a four-wheeled motorized vehicle with an enclosed passenger area and a steering wheel.",
        "A car typically has four wheels, an engine, a steering wheel, a driver's seat, and various other components such as brakes, suspension, and a transmission.",
        "A car typically has four wheels, an engine, a transmission, a steering wheel, a braking system, headlights, taillights, a dashboard, seats, and a roof.",
        "A car typically has four wheels, an engine, a steering wheel, a gear shift, brake pedals, and a variety of other parts that allow it to operate.",
        "A car has a long, sleek body with a pointed front end and curved sides.",
        "A car has four wheels, an engine, a body, and various other components such as brakes, steering wheel, and seats.",
        "A car typically has four wheels, an engine, a steering wheel, a brake pedal, and seats for passengers.",
        "A car has four wheels, an engine, a steering wheel, brakes, a gas pedal, a gear shift (for manual transmission cars), and various other features such as headlights, taillights, a windsh.",
        "A car has four wheels, an engine, a steering wheel, a brake pedal, a gear shift, headlights, taillights, a windshield, a roof, a trunk, and seats.",
        "A car is a four-wheeled, motorized vehicle with a unique visual appearance characterized by A sleek, aerodynamic body, B distinctive headlights and taillights, C a recognizable and stylish logo.",
        "A car is a four-wheeled vehicle with a unique visual appearance that can be described as sleek, aerodynamic, and futuristic.",
        "A car is a four-wheeled vehicle with a unique visual appearance that typically includes features such as a distinctive body shape, colors, and design elements.",
        "A car is sleek, aerodynamic, and shiny.",
        "A car is sleek, aerodynamic, and sporty, featuring a low and wide stance with smooth curves and sharp angles.",
        "A car is a four-wheeled, generally rectangular-shaped vehicle with a variety of visual features that make it unique.",
        "A car is sleek, modern, and aerodynamic, with a distinctive grille, sharp lines, and bright headlights.",
        "A car is a four-wheeled motor vehicle that is primarily used for transportation.",
        "A car is a four-wheeled vehicle with a unique visual appearance that typically includes the following features: sleek and streamlined body, shiny and reflective exterior, distinctive and recognizable silhouette, colorful and bold.",
        "A car is a four-wheeled motor vehicle with a distinctive visual appearance that can be described using the following adjective phrases:* Shaped like a box or rectangular prism, with straight lines and right angles."
    ],
    "truck": [
        "A truck has a large, rectangular-shaped body, a flatbed, a chassis, and wheels.",
        "A truck has a large, boxy body with a flatbed or enclosed cargo area, a long wheelbase, and large wheels.",
        "A truck typically has a large, rectangular-shaped cab for the driver and passenger(s), a flatbed or enclosed trailer attached to the back for hauling cargo, and a chassis underneath for support and.",
        "A truck, also known as a commercial motor vehicle, typically has the following features:* A large and sturdy body, often made of metal and measuring several meters in length and width.",
        "A truck has a large, sturdy frame, a solid, flatbed or enclosed cargo area, four wheels, a robust suspension system, and a powerful engine.",
        "A truck has a large, rectangular-shaped body with flat sides and a rear cargo bed.",
        "A truck has a large, sturdy body, a flat bed or enclosed cab, and four wheels.",
        "A truck typically has a large, rectangular body with flat sides and a sliding door on one side.",
        "A truck has a large, sturdy body, a flatbed or enclosed cargo area, a robust chassis, powerful wheels, and a distinctive enginesound.",
        "A truck has a cabin in the front, a flatbed or a box-shaped cargo area, and four wheels.",
        "A truck is large, sturdy, and rugged.",
        "A truck is typically a large, sturdy, and utilitarian vehicle with a distinctive visual appearance.",
        "A truck is a large, powerful, and sturdy vehicle with a distinctive visual appearance that sets it apart from other types of vehicles.",
        "A truck is typically a large, boxy vehicle with a flatbed or enclosed cargo area, a long wheelbase, and a distinctive grille.",
        "a large, boxy vehicle with a long bed and heavy-duty suspension, typically painted in a shade of silver or blue with bold lettering on the sides indicating the company or organization it is used by.",
        "A truck is a large, wheeled vehicle designed for transporting goods or materials.",
        "A truck is a large, heavy vehicle with a flatbed or enclosed cargo area, and typically has four wheels.",
        "A truck is typically a large, boxy vehicle with a angular and muscular appearance.",
        "A truck is a large, heavy vehicle with a box-shaped bed and four wheels.",
        "A truck is a large, sturdy vehicle with a flatbed or enclosed cargo area, a powerful engine, and a distinctive visual appearance that includes features such as a square or rectangular shape, large tires, and a high."
    ],
    "bus": [
        "A bus typically has the following features:* A long, rectangular shape with a flat bottom and sides* A front end with a rounded shape and a window for the driver to see out of* A door or doors in the.",
        "A bus typically has:* A long, rectangular body with windows on both sides* A front windshield and a rear window or windows* A flat or sloping roof* A front bumper and a.",
        "A bus has a long, rectangular body with sleek lines, a front windshield, and a rear window.",
        "A bus typically has a long, rectangular body with a front windshield, a rear window, and bus doors on both sides.",
        "An bus typically has a rectangular shape with a front and back end, a long and narrow body, two axles, a steering wheel, an engine, front and back wheels, a sliding door for passengers to board and exit,.",
        "A bus has a long, rectangular body with a flat front and rear and two side panels.",
        "A bus typically has a large, rectangular body with a flat bottom and sides that curve upwards towards the front.",
        "A bus has a long, rectangular body with a flat front, a sloped roof, and windows along the sides.",
        "A bus has a long, rectangular body with a flat front and a sloping roof.",
        "A bus has a long, rectangular body with a flat front and rear, a high roof, and large windows.",
        "A bus is rectangular, with a long, narrow body and large windows.",
        "A bus is typically a large, rectangular-shaped vehicle with a flat front end and a sloping rear.",
        "A bus is typically a large, rectangular-shaped vehicle with a flat front end and a raised roof.",
        "A bus is typically a large, rectangular-shaped vehicle with a raised front, large windows, and a flat bottom.",
        "A bus is a large, rectangular-shaped vehicle with long narrow sides, a sloped front, and an engine on the bottom.",
        "A bus is a large, rectangular-shaped vehicle with a flat front and rear, a high roofline, and windows on both sides.",
        "A bus is a large, rectangular-shaped vehicle with an elongated nose and a flat front end, typically equipped with large windows and multiple entry/exit doors.",
        "A bus is a large, rectangular-shaped vehicles with a long front and rear overhangs, a flat base and sides, and a maximum height that varies between 3.",
        "A bus is a large, rectangular-shaped vehicle with a long, curved front end and a flat back end.",
        "A bus is a large, rectangular-shaped vehicle with a flat front and a sloping nose, often featuring a logo or name on the front and sides."
    ],
    "train": [
        "A train has:* A long, rectangular-shaped body with a flat bottom and high sides* B metal wheels, attached to the heavy steel rails for movement* C a long engine at the front, which push.",
        "A train has:* A long, rectangular shape* A series of connected cars or wagons* A locomotive at the front to provide power* Wheels that allow it to move on tracks* A horn.",
        "A train has a long, rectangular shape with a flat bottom and a curved top.",
        "A train has:* A locomotive: This is the front car or engine that provides the power to move the train forward.",
        "A train has a long, metal body that is typically painted in a specific color, such as red, blue, or green.",
        "A train has:* A long, steel or aluminum frame with wheels on either end* B multiple cars or coaches, each with a capacity to seat or stand numerous passengers* C an engine at the front,.",
        "A train has:* A collection of railroad cars, typically connected together and powered by an engine.",
        "A train has:* An engine, which is typically a large, orange and grey machine with a cab for the operator* A series of railcars or coaches, which can be passenger cars or cargo cars, and typically have.",
        "A train typically consists of a long, rectangular-shaped locomotive, a series of connected railway cars, and sometimes a cabin or caboose at the end of the train.",
        "A train typically consists of:* A long and wide locomotive at the front, which houses the engine and controls that propel the train forward.",
        "A train is a long, metal vehicle with a series of connected passenger or cargo cars, usually powered by electricity or diesel fuel.",
        "A train is a long, rectangular object with a series of connected cars, each with a few windows and a door.",
        "A train is a large, metal vehicle with a long, bent body and several cars attached to it.",
        "A train is a long, metallic vehicle with multiple cars connected together, typically pulled or pushed by a locomotive at the front.",
        "A train is elongated, metallic, and often painted in a specific color scheme, with varying numbers of cars, each containing windows and potentially doors, and sometimes featuring designs or logos on the exterior.",
        "A train is a long, sleek vehicle with a brightly-colored exterior and a series of connected cars.",
        "A train is a long, metallic vehicle with a series of connected cars, each containing seating or cargo areas.",
        "A train is a long, rectangular-shaped vehicle with a series of connected cars or compartments that runs on a track.",
        "A train is a long, sleek, silvery vehicle with a brightly lit cabin and a series of cars connected by a red or blue line.",
        "A train is an elongated, metallic vehicle with a series of connected cargo or passenger cars, often pulled by a locomotive at the front."
    ],
    "motorcycle": [
        "A motorcycle typically has two wheels, an engine, a frame or chassis, a seat, handlebars, a fuel tank, and various other components such as brakes, suspension, and lights.",
        "A motorcycle is a two-wheeled, motorized vehicle that has an engine, a seat, a handlebar, a transmission, a rear suspension, a fuel tank, and a exhaust system.",
        "A motorcycle is a two-wheeled vehicle with an engine, a frame, and a seat for the rider.",
        "A motorcycle has:* Two wheels* An engine* A frame or chassis* A seat* Handlebars* A fuel tank* Headlight* Taillight* Turn signals.",
        "A motorcycle has two wheels, an engine, a frame, handlebars, a gas tank, and a seat.",
        "A motorcycle has two wheels, an engine, a seat, handlebars, and a frame.",
        "A motorcycle has two wheels, an engine, a frame, handlebars, a seat, and various other amenities such as mirrors, lights, and a fuel tank.",
        "A motorcycle typically has two wheels, an engine, a seat, handlebars, a fuel tank, and a body or frame.",
        "A motorcycle has two wheels, a handlebar, a petrol tank, an engine, a seat, and a rear fender.",
        "A motorcycle has a two-wheeled frame, an engine, a seat, handlebars, and a variety of styling features such as mudguards, headlights, and taillights.",
        "A motorcycle is a two-wheeled, aerodynamic vehicle with an engine and a frame, featuring sleek bodywork, a distinctive fuel tank, and a long, narrow seat for the rider.",
        "A motorcycle is a two-wheeled vehicle with an engine, aframe, and handlebars.",
        "A motorcycle is sleek, powerful, and maneuverable, comprising a small, high-performance vehicle designed for two-wheeled travel.",
        "A motorcycle is a two-wheeled vehicle with an engine, a seat, handlebars, and a fuel tank.",
        "A motorcycle is a two-wheeled vehicle with an engine, a seat, handlebars, and pedals.",
        "A motorcycle is sleek, powerful, and maneuverable.",
        "A motorcycle is a two-wheeled vehicle with an engine and a saddle for the rider.",
        "A motorcycle is a two-wheeled, high-performance vehicle with an engine and a distinctive appearance that sets it apart from other vehicles on the road.",
        "A motorcycle is a two-wheeled vehicle with an engine, a distinct silhouette, and multiple design features that contribute to its unique visual appearance.",
        "A motorcycle is sleek, speedy, and agile."
    ],
    "bicycle": [
        "a bicycle has two wheels, a frame, a saddle, handlebars, pedals, and a chain.",
        "A bicycle typically has two wheels, a frame or handlebars, a seat, pedals, and a chain or belt drive system.",
        "A bicycle has:* Two wheels* Pedals* A frame* A handlebar* A saddle* A drivetrain (chain, gears, crankset)* A bra.",
        "A bicycle is a two-wheeled vehicle that has a frame, wheels, handlebars, a saddle, pedals, and sometimes a basket or luggage rack.",
        "A bicycle has two wheels, a frame, handlebars, a saddle, pedals, and a chain.",
        "A bicycle has:1.",
        "A bicycle has two wheels, a frame, handlebars, a saddle, pedals, and a chain.",
        "A bicycle has:* Two wheels* A frame* Pedals* A saddle* Handlebars* A chain* A chainring.",
        "a bicycle has two wheels, a frame, handlebars, a saddle, pedals, and a drivetrain.",
        "A bicycle has two wheels, a frame, pedals, a seat, handlebars, and a brake system.",
        "A bicycle is a wheeled vehicle with two pedals and a saddle, designed for human propulsion.",
        "A bicycle is a two-wheeled, pedal-powered vehicle with a frame, handlebars, and a saddle.",
        "A bicycle is two-wheeled, pedal-powered, with a frame, handlebars, and a saddle.",
        "A bicycle is two-wheeled, human-powered, and frequently seen on streets and trails around the world.",
        "The unique visual appearance of a bicycle can be described using the following adjective phrases:* two-wheeled* having a diamond-shaped frame* with pedals and a crankset.",
        "A bicycle is typically a two-wheeled vehicle with a frame, pedals, and handlebars.",
        "A bicycle is a two-wheeled, human-powered vehicle with pedals and a saddle.",
        "A bicycle is a multi- wheel transportation device, typically designed for one person, with pedals that are used to propel the vehicle forward.",
        "A bicycle is typically a two-wheeled vehicle with a frame, handlebars, pedals, and a saddle.",
        "A bicycle is two-wheeled, pedal-powered, and often has a unique visual appearance that sets it apart from other modes of transportation."
    ]
}